on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm init -y
      run: npm init -y
    - name: npm install typescript-bundle
      run: npm install typescript-bundle
    - name: npx tsc-bundle tsconfig.json
      run: npx tsc-bundle tsconfig.json
    - name: git add ./html/bundle.js
      run: git add ./html/bundle.js
    - name: git commit -m "build typescript"
      run: git commit -m "build typescript"
    - name: git push origin master
      run: git push origin master
