on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm init -y
      run: npm init -y
    - name: npm install typescript-bundle
      run: npm install typescript-bundle
    - name: npx tsc-bundle tsconfig.json
      run: npx tsc-bundle tsconfig.json
    - name: commit changed files
      run: 
        git config --global user.email "thejoecapewell@gmail.com"
        git config --global user.name "Joe Capewell"
        git remote add origin git@github.com:ScooScoot/scooscoot.github.io.git
        git add ./html/bundle.js
        git commit -m "build typescript"
        git push origin master
